services:
  professores:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sme_sgp_ms_professores
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    ports:
      - "8001:8000"
    restart: unless-stopped
