services:
  professores:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sme_sgp_ms_professores_dev
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    volumes:
      - .:/app
    command: >
      python -Xfrozen_modules=off -m debugpy
      --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8001
    ports:
      - "${PORT_WEB:-8001}:${PORT_WEB:-8001}"
      - "${PORT_DEBUGPY:-5678}:${PORT_DEBUGPY:-5678}"
    restart: unless-stopped
