[project]
name = 'SME-SGP-MS-Professores'
version = '0.1.0'
description = 'MS responsável por expor dados de professores de forma somente leitura, a partir de bases previamente tratadas por processos de ETL'
requires-python = '>=3.12'

[tool.black]
line-length = 79
target-version = ["py311"]
 
[tool.isort]
profile = "black"
line_length = 79
[tool. Ruff]
line-length = 79
 
[tool.ruff.lint]
select = [
  "E",  # pycodestyle (PEP 8)
  "F",  # pyflakes
  "D",  # pydocstyle (PEP 257)
]
 
ignore = [
  "E501",  # line length (black já resolve)
]
 
[tool.ruff.lint.pydocstyle]
convention = "google"
 
[tool.mypy]
python_version = 3.11
strict = true
 
ignore_missing_imports = true
warn_unused_ignores = true
warn_return_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true